//
//  Icon.swift
//  Shortcuts
//
//  Created by Kenna Blackburn on 2/11/26.
//

import Foundation

public struct Icon: Encodable {
    public var glyph: Glyph
    public var color: Color
    
    public init(glyph: Glyph, color: Color) {
        self.glyph = glyph
        self.color = color
    }
    
    public init(_ color: Color, _ glyph: Glyph) {
        self.init(glyph: glyph, color: color)
    }
}

extension Icon {
    public struct Glyph: Encodable, Sendable {
        public var id: Int
        
        public init(_ id: Int) {
            self.id = id
        }
        
        public func encode(to encoder: any Encoder) throws {
            try id.encode(to: encoder)
        }
    }
}

// i didn't verify these, i just copied them from https://github.com/electrikmilk/cherri/blob/main/glyphs.go
extension Icon.Glyph {
    static let car: Self                        = .init(59452)
    static let carMultiple: Self                = .init(61446)
    static let electricCar: Self                = .init(61447)
    static let bus: Self                        = .init(59678)
    static let busDouble: Self                  = .init(61448)
    static let tram: Self                       = .init(61449)
    static let tramTunnel: Self                 = .init(61450)
    static let bike: Self                       = .init(59668)
    static let motorcycle: Self                 = .init(59783)
    static let ambulance: Self                  = .init(59652)
    static let airplane: Self                   = .init(59648)
    static let sailboat: Self                   = .init(59823)
    static let house: Self                      = .init(59755)
    static let church: Self                     = .init(59688)
    static let buildings: Self                  = .init(59677)
    static let shoppingCart: Self               = .init(59828)
    static let handbag: Self                    = .init(59750)
    static let groceryStore: Self               = .init(59747)
    static let utensils: Self                   = .init(59863)
    static let fuelstation: Self                = .init(59741)
    static let thermometer: Self                = .init(59854)
    static let sun: Self                        = .init(59845)
    static let moon: Self                       = .init(59782)
    static let moonCircle: Self                 = .init(61517)
    static let snowflake: Self                  = .init(59835)
    static let cloud: Self                      = .init(59714)
    static let raincloud: Self                  = .init(59715)
    static let umbrella: Self                   = .init(59861)
    static let pineTree: Self                   = .init(59731)
    static let flower: Self                     = .init(59468)
    static let fire: Self                       = .init(59734)
    static let footprints: Self                 = .init(59738)
    static let signs: Self                      = .init(59724)
    static let binoculars: Self                 = .init(59669)
    static let compass: Self                    = .init(59717)
    static let globe: Self                      = .init(59412)
    static let mountain: Self                   = .init(59785)
    static let picture: Self                    = .init(59784)
    static let filmstrip: Self                  = .init(59733)
    static let camera: Self                     = .init(59682)
    static let movieCamera: Self                = .init(59402)
    static let microphone: Self                 = .init(59780)
    static let videoIcon: Self                  = .init(59864)
    static let clipboard: Self                  = .init(59711)
    static let calendar: Self                   = .init(59681)
    static let chatBubble: Self                 = .init(59414)
    static let messageBubbles: Self             = .init(59403)
    static let textBubble: Self                 = .init(59779)
    static let envelope: Self                   = .init(59773)
    static let envelopeOpen: Self               = .init(59774)
    static let paperAirplane: Self              = .init(59836)
    static let paperAirplaneCircle: Self        = .init(61462)
    static let briefcase: Self                  = .init(59676)
    static let folder: Self                     = .init(59737)
    static let creditCard: Self                 = .init(59719)
    static let watch: Self                      = .init(59865)
    static let phone: Self                      = .init(59814)
    static let laptop: Self                     = .init(59436)
    static let keyboard: Self                   = .init(59446)
    static let keyboardOld: Self                = .init(59494)
    static let calculator: Self                 = .init(59680)
    static let barGraph: Self                   = .init(59662)
    static let printer: Self                    = .init(59817)
    static let hardDrive: Self                  = .init(59752)
    static let server: Self                     = .init(59722)
    static let database: Self                   = .init(59519)
    static let networkStorage: Self             = .init(59826)
    static let archive: Self                    = .init(59653)
    static let cube: Self                       = .init(59721)
    static let tv: Self                         = .init(59851)
    static let gameController: Self             = .init(59742)
    static let puzzlePiece: Self                = .init(59818)
    static let headphones: Self                 = .init(59753)
    static let headphonesCircle: Self           = .init(61479)
    static let ear: Self                        = .init(61481)
    static let musicNote: Self                  = .init(59790)
    static let volumeLow: Self                  = .init(59839)
    static let volumeMid: Self                  = .init(61470)
    static let volumeHigh: Self                 = .init(61471)
    static let mute: Self                       = .init(61472)
    static let speaker: Self                    = .init(61473)
    static let hifiSpeaker: Self                = .init(61478)
    static let desktopSpeaker: Self             = .init(61474)
    static let bookshelf: Self                  = .init(59671)
    static let openBook: Self                   = .init(59465)
    static let sashBook: Self                   = .init(59672)
    static let closedBook: Self                 = .init(61442)
    static let glasses: Self                    = .init(59745)
    static let mask: Self                       = .init(59777)
    static let ticket: Self                     = .init(59788)
    static let dramaMask: Self                  = .init(59730)
    static let dice: Self                       = .init(59723)
    static let baseball: Self                   = .init(59663)
    static let basketball: Self                 = .init(59664)
    static let soccerBall: Self                 = .init(59837)
    static let tennisBall: Self                 = .init(59852)
    static let football: Self                   = .init(59456)
    static let lifePreserver: Self              = .init(59762)
    static let telescope: Self                  = .init(59850)
    static let microscope: Self                 = .init(59781)
    static let horse: Self                      = .init(59756)
    static let clock: Self                      = .init(59712)
    static let alarmClock: Self                 = .init(59649)
    static let stopwatch: Self                  = .init(59844)
    static let bell: Self                       = .init(59667)
    static let sparklingBell: Self              = .init(59838)
    static let heart: Self                      = .init(59754)
    static let star: Self                       = .init(59841)
    static let trophy: Self                     = .init(59860)
    static let lightbulb: Self                  = .init(59763)
    static let lightningBolt: Self              = .init(59764)
    static let flag: Self                       = .init(59736)
    static let tag: Self                        = .init(59848)
    static let key: Self                        = .init(59760)
    static let hourglass: Self                  = .init(59757)
    static let lock: Self                       = .init(59770)
    static let unlockButton: Self               = .init(59862)
    static let battery: Self                    = .init(59489)
    static let magicWand: Self                  = .init(59511)
    static let magicWandAlt: Self               = .init(59771)
    static let paintbrush: Self                 = .init(59793)
    static let pencil: Self                     = .init(59798)
    static let paperclip: Self                  = .init(59794)
    static let scissors: Self                   = .init(59824)
    static let magnifyingGlass: Self            = .init(59772)
    static let chainlink: Self                  = .init(59685)
    static let eyedropper: Self                 = .init(59716)
    static let hammer: Self                     = .init(59748)
    static let wrench: Self                     = .init(59870)
    static let tools: Self                      = .init(59749)
    static let gear: Self                       = .init(59743)
    static let hammerAlt: Self                  = .init(59473)
    static let screwdriver: Self                = .init(59825)
    static let hand: Self                       = .init(59751)
    static let trashcan: Self                   = .init(59859)
    static let waterDrop: Self                  = .init(59866)
    static let mug: Self                        = .init(59789)
    static let steamingBowl: Self               = .init(59842)
    static let apple: Self                      = .init(59740)
    static let carrot: Self                     = .init(59683)
    static let fish: Self                       = .init(59735)
    static let cake: Self                       = .init(59679)
    static let wineBottle: Self                 = .init(59868)
    static let martini: Self                    = .init(59776)
    static let clothesHanger: Self              = .init(59713)
    static let laundryMachine: Self             = .init(59761)
    static let oven: Self                       = .init(59792)
    static let shirt: Self                      = .init(59827)
    static let bathtub: Self                    = .init(59665)
    static let shower: Self                     = .init(59829)
    static let pill: Self                       = .init(59461)
    static let medicine: Self                   = .init(59815)
    static let medicineBottle: Self             = .init(59778)
    static let bandage: Self                    = .init(59660)
    static let inhaler: Self                    = .init(59759)
    static let stethoscope: Self                = .init(59843)
    static let syringe: Self                    = .init(59847)
    static let atom: Self                       = .init(59657)
    static let chemical: Self                   = .init(59686)
    static let cat: Self                        = .init(59684)
    static let dog: Self                        = .init(59728)
    static let pawPrint: Self                   = .init(59796)
    static let thumbsUp: Self                   = .init(59857)
    static let graduate: Self                   = .init(59746)
    static let gift: Self                       = .init(59744)
    static let alien: Self                      = .init(59651)
    static let bed: Self                        = .init(59666)
    static let stairs: Self                     = .init(59840)
    static let rocket: Self                     = .init(59822)
    static let map: Self                        = .init(61444)
    static let gauge: Self                      = .init(61452)
    static let speedometer: Self                = .init(61453)
    static let barometer: Self                  = .init(61454)
    static let network: Self                    = .init(61455)
    static let rectangleStack: Self             = .init(61456)
    static let squareStack: Self                = .init(61457)
    static let threeDSquareStack: Self          = .init(61458)
    static let photoStack: Self                 = .init(61459)
    static let photoStackAlt: Self              = .init(61460)
    static let aperture: Self                   = .init(61461)
    static let note: Self                       = .init(61464)
    static let noteText: Self                   = .init(61465)
    static let noteTextPlus: Self               = .init(61466)
    static let sendMessage: Self                = .init(61467)
    static let addMessage: Self                 = .init(61468)
    static let earPods: Self                    = .init(61475)
    static let airPods: Self                    = .init(61476)
    static let airPodsPro: Self                 = .init(61477)
    static let radio: Self                      = .init(61480)
    static let appleTV: Self                    = .init(61482)
    static let homePod: Self                    = .init(61483)
    static let appleWatchWaves: Self            = .init(61484)
    static let iPhone: Self                     = .init(61486)
    static let iPhoneWave: Self                 = .init(61487)
    static let iPhoneApps: Self                 = .init(61488)
    static let iPad: Self                       = .init(61489)
    static let iPadAlt: Self                    = .init(61490)
    static let iPod: Self                       = .init(61491)
    static let babyGirl: Self                   = .init(59658)
    static let babyBoy: Self                    = .init(59659)
    static let child: Self                      = .init(59687)
    static let man: Self                        = .init(59775)
    static let woman: Self                      = .init(59869)
    static let wheelchair: Self                 = .init(59806)
    static let person: Self                     = .init(59801)
    static let people2: Self                    = .init(59800)
    static let people3: Self                    = .init(59799)
    static let person2: Self                    = .init(59437)
    static let personAlter: Self                = .init(59802)
    static let personSpeech: Self               = .init(59804)
    static let personDancer: Self               = .init(59803)
    static let personLifting: Self              = .init(59807)
    static let personSkiing: Self               = .init(59809)
    static let personSnowboarding: Self         = .init(59810)
    static let personSwimming: Self             = .init(59811)
    static let personHiking: Self               = .init(59805)
    static let personWalking: Self              = .init(59812)
    static let personWalkingCane: Self          = .init(59813)
    static let personRunning: Self              = .init(59808)
    static let personRunningCircle: Self        = .init(61493)
    static let personSprinting: Self            = .init(61494)
    static let personClose: Self                = .init(61495)
    static let personOpen: Self                 = .init(61496)
    static let shortcuts: Self                  = .init(61440)
    static let alertTriangle: Self              = .init(59650)
    static let arrowCurvedLeft: Self            = .init(59654)
    static let arrowCurvedRight: Self           = .init(59655)
    static let bookmark: Self                   = .init(59670)
    static let barcode: Self                    = .init(59661)
    static let qrCode: Self                     = .init(59819)
    static let play: Self                       = .init(59508)
    static let boxFilled: Self                  = .init(59673)
    static let boxOutline: Self                 = .init(59674)
    static let braille: Self                    = .init(59675)
    static let circleLeftArrow: Self            = .init(59696)
    static let circleRightArrow: Self           = .init(59705)
    static let downloadArrow: Self              = .init(59693)
    static let circledUpArrow: Self             = .init(59707)
    static let circledDownArrow: Self           = .init(59692)
    static let uploadArrow: Self                = .init(59708)
    static let circledPlay: Self                = .init(59699)
    static let circledRewind: Self              = .init(59704)
    static let circledPower: Self               = .init(59702)
    static let circledStop: Self                = .init(59706)
    static let circledFastForward: Self         = .init(59695)
    static let circledQuestionMark: Self        = .init(59703)
    static let circledCheckmark: Self           = .init(59690)
    static let circledPlus: Self                = .init(59700)
    static let circledX: Self                   = .init(59709)
    static let circledPi: Self                  = .init(59698)
    static let circledI: Self                   = .init(59697)
    static let smileyFace: Self                 = .init(59834)
    static let document: Self                   = .init(59725)
    static let dollarSign: Self                 = .init(59395)
    static let poundSign: Self                  = .init(59512)
    static let euroSign: Self                   = .init(59448)
    static let yenSign: Self                    = .init(59514)
    static let bitcoin: Self                    = .init(59515)
    static let asterisk: Self                   = .init(59656)
    static let documentFilled: Self             = .init(59726)
    static let documentOutline: Self            = .init(59727)
    static let newsArticle: Self                = .init(59791)
    static let fourSquares: Self                = .init(59739)
    static let ellipsis: Self                   = .init(59392)
    static let list: Self                       = .init(59445)
    static let twelveSquares: Self              = .init(59405)
    static let connected: Self                  = .init(59718)
    static let infinity: Self                   = .init(59758)
    static let recycle: Self                    = .init(59820)
    static let loadingIndicator: Self           = .init(59767)
    static let loadingIndicatorAlt: Self        = .init(59516)
    static let target: Self                     = .init(59849)
    static let podcasts: Self                   = .init(59816)
    static let targetAlt: Self                  = .init(59454)
    static let locationArrow: Self              = .init(59768)
    static let locationPin: Self                = .init(59769)
    static let parking: Self                    = .init(59795)
    static let crop: Self                       = .init(59720)
    static let shrinkArrow: Self                = .init(59830)
    static let moveArrow: Self                  = .init(59786)
    static let repostArrows: Self               = .init(59821)
    static let syncArrows: Self                 = .init(59846)
    static let shuffleArrows: Self              = .init(59832)
    static let sliders: Self                    = .init(59833)
    static let doubleQuote: Self                = .init(59729)
    static let peaceSign: Self                  = .init(59797)
    static let threeCircles: Self               = .init(59856)
    static let textSymbol: Self                 = .init(59853)
    static let feedRight: Self                  = .init(59732)
    static let feed: Self                       = .init(59497)
    static let wifi: Self                       = .init(59867)
    static let airdrop: Self                    = .init(61501)
    static let arrowDiamond: Self               = .init(61497)
    static let directionsRight: Self            = .init(61498)
    static let airplayAudio: Self               = .init(61499)
    static let airplayVideo: Self               = .init(61500)
    static let musicNoteList: Self              = .init(61502)
    static let musicNoteAlt: Self               = .init(61503)
    static let musicSquareStack: Self           = .init(61504)
    static let musicWaveForm: Self              = .init(61505)
    static let livePlay: Self                   = .init(61506)
    static let livePhoto: Self                  = .init(61507)
    static let sloMo: Self                      = .init(61508)
    static let timeLapse: Self                  = .init(61509)
    static let calendarPlus: Self               = .init(61510)
    static let calendarExclamation: Self        = .init(61511)
    static let timer: Self                      = .init(61512)
    static let timerSquare: Self                = .init(61513)
    static let compose: Self                    = .init(61514)
    static let duplicate: Self                  = .init(61515)
    static let nightShift: Self                 = .init(61518)
    static let trueTone: Self                   = .init(61519)
    static let dialMin: Self                    = .init(61520)
    static let dialMax: Self                    = .init(61521)
    static let qrViewFinder: Self               = .init(61522)
    static let cameraViewFinder: Self           = .init(61523)
    static let walletPass: Self                 = .init(61524)
    static let appearance: Self                 = .init(61525)
    static let noSign: Self                     = .init(61528)
    static let command: Self                    = .init(61529)
    static let commandCircle: Self              = .init(61530)
    static let commandSquare: Self              = .init(61531)
    static let bumps: Self                      = .init(59433)
    static let stripe: Self                     = .init(59455)
    static let facetime: Self                   = .init(59583)
    static let circledHeart: Self               = .init(59542)
    static let documentOutlineAlt: Self         = .init(59496)
    static let circledA: Self                   = .init(59520)
    static let folderGear: Self                 = .init(61571)
    static let folderOutline: Self              = .init(61570)
    static let takeout: Self                    = .init(61553)
    static let starHalf: Self                   = .init(61579)
    static let sparkles: Self                   = .init(61581)
    static let surgicalMask: Self               = .init(61551)
    static let bear: Self                       = .init(61554)
    static let tiger: Self                      = .init(61555)
    static let monkey: Self                     = .init(61556)
    static let ram: Self                        = .init(61557)
    static let rabbit: Self                     = .init(61558)
    static let snake: Self                      = .init(61559)
    static let chicken: Self                    = .init(61560)
    static let pig: Self                        = .init(61561)
    static let mouse: Self                      = .init(61562)
    static let cow: Self                        = .init(61563)
    static let dragon: Self                     = .init(61564)
    static let retroAlien: Self                 = .init(61565)
    static let robot: Self                      = .init(61566)
    static let ghost: Self                      = .init(61567)
    static let poop: Self                       = .init(61568)
    static let skull: Self                      = .init(61569)
    static let twoxTwoRectangles: Self          = .init(61572)
    static let twoxTwoRectanglesOutline: Self   = .init(61573)
    static let rectangleSplit: Self             = .init(61574)
    static let rectangleSplitThree: Self        = .init(61575)
    static let rectangleSplitThreeOutline: Self = .init(61576)
    static let sendMessageOutline: Self         = .init(61582)
    static let brainHead: Self                  = .init(61532)
    static let brain: Self                      = .init(61533)
    static let faceGrinning: Self               = .init(61534)
    static let faceSmiling: Self                = .init(61535)
    static let faceGrinningSquint: Self         = .init(61536)
    static let faceTears: Self                  = .init(61537)
    static let faceRolling: Self                = .init(61538)
    static let faceWink: Self                   = .init(61539)
    static let faceGrimacing: Self              = .init(61540)
    static let faceLove: Self                   = .init(61541)
    static let faceKiss: Self                   = .init(61542)
    static let faceHearts: Self                 = .init(61543)
    static let faceSunglasses: Self             = .init(61544)
    static let faceStarry: Self                 = .init(61545)
    static let memoji: Self                     = .init(61546)
    static let handSlash: Self                  = .init(61584)
    static let handSlashOutline: Self           = .init(61585)
    static let thumbsUpEmoji: Self              = .init(61547)
    static let peace: Self                      = .init(61548)
    static let loveGesture: Self                = .init(61549)
    static let closedFist: Self                 = .init(61550)
    static let xSquare: Self                    = .init(61589)
    static let checklist: Self                  = .init(61587)
    static let doubleQuoteOutline: Self         = .init(61583)
    static let textBox: Self                    = .init(61588)
    static let waveform: Self                   = .init(61586)
    static let oneProngPuzzlePiece: Self        = .init(61552)
    static let cartoonHeart: Self               = .init(61577)
    static let twoCartoonHearts: Self           = .init(61578)
    static let cloudService: Self               = .init(59459)
    static let keyRadiowaves: Self              = .init(62212)
    static let appleIntelligence: Self          = .init(62213)
    static let handPointUpLeft: Self            = .init(62214)
    static let handTap: Self                    = .init(62215)
    static let handDraw: Self                   = .init(62216)
    static let shippingBox: Self                = .init(62217)
    static let engineCombustion: Self           = .init(62224)
    static let pc: Self                         = .init(62225)
    static let bellBadge: Self                  = .init(62226)
    static let bellAnnounce: Self               = .init(62227)
    static let bellSlash: Self                  = .init(62228)
    static let bellAndWaves: Self               = .init(62229)
    static let swatchPalette: Self              = .init(62230)
    static let mugAlt: Self                     = .init(62231)
    static let oilCan: Self                     = .init(62232)
    static let newspaper: Self                  = .init(62233)
    static let a11y: Self                       = .init(62240)
    static let megaphone: Self                  = .init(62241)
    static let shieldSwap: Self                 = .init(62242)
    static let basket: Self                     = .init(62243)
    static let level: Self                      = .init(62244)
    static let fileVault: Self                  = .init(62245)
    static let fireplace: Self                  = .init(62246)
    static let cabinet: Self                    = .init(62247)
    static let dryer: Self                      = .init(62248)
    static let sink: Self                       = .init(62249)
    static let pin: Self                        = .init(62256)
    static let shoe: Self                       = .init(62257)
    static let buildingBlock: Self              = .init(62258)
    static let dPad: Self                       = .init(62259)
    static let waterBottle: Self                = .init(62260)
    static let sdCard: Self                     = .init(62261)
    static let sdCard2: Self                    = .init(62262)
    static let chip: Self                       = .init(62263)
    static let weight: Self                     = .init(62264)
    static let dollar: Self                     = .init(62265)
    static let yoyo: Self                       = .init(62272)
    static let americanFootball: Self           = .init(62273)
    static let americanFootballStriped: Self    = .init(62274)
    static let beachUmbrella: Self              = .init(62275)
    static let spade: Self                      = .init(62276)
    static let club: Self                       = .init(62278)
    static let showerHandheld: Self             = .init(62279)
    static let signpostRight: Self              = .init(62280)
    static let macProGen3: Self                 = .init(62281)
    static let macProGen2: Self                 = .init(62288)
    static let macProGen1: Self                 = .init(62289)
    static let homepodMini: Self                = .init(62290)
    static let homepod2: Self                   = .init(62291)
    static let carSideSUV: Self                 = .init(62292)
    static let carSideSedan: Self               = .init(62293)
    static let carSideConvertable: Self         = .init(62294)
    static let hornBlast: Self                  = .init(62295)
    static let vaccinationCard: Self            = .init(62296)
    static let ivFluidBag: Self                 = .init(62297)
    static let hatWideBrim: Self                = .init(62304)
    static let globeDesk: Self                  = .init(62305)
    static let mugHot: Self                     = .init(62306)
    static let networkConnected: Self           = .init(62307)
    static let appConnection: Self              = .init(62308)
    static let mustache: Self                   = .init(62310)
    static let flipPhone: Self                  = .init(62311)
    static let siri: Self                       = .init(62312)
    static let appStore: Self                   = .init(62313)
    static let carPlay: Self                    = .init(62320)
    static let textAppend: Self                 = .init(62321)
    static let appleCash: Self                  = .init(62322)
    static let appleMathNotes: Self             = .init(62323)
    static let appleMindfulness: Self           = .init(62324)
    static let appleBreathe: Self               = .init(62325)
    static let appleReflect: Self               = .init(62326)
    static let appleMeditate: Self              = .init(62327)
    static let appleStateOfMind: Self           = .init(62328)
    static let appleCycleTracking: Self         = .init(62329)
    static let appleNews: Self                  = .init(62336)
    static let appleHealthTrends: Self          = .init(62337)
    static let applePages: Self                 = .init(62338)
    static let appleKeynote: Self               = .init(62339)
    static let appleNumbers: Self               = .init(62340)
    static let bezierCurve: Self                = .init(62341)
    static let roadCurvedLeft: Self             = .init(62342)
    static let roadCurvedRight: Self            = .init(62343)
    static let pointsConnection: Self           = .init(62344)
    static let pointsCurvedSPath: Self          = .init(62345)
    static let sparkle: Self                    = .init(62352)
    static let arrowUpRight: Self               = .init(62353)
    static let arrowUpLeft: Self                = .init(62354)
    static let textInsert: Self                 = .init(62355)
    static let textQuote: Self                  = .init(62356)
    static let textAlignLeft: Self              = .init(62357)
    static let textAlignCenter: Self            = .init(62358)
    static let textAlignRight: Self             = .init(62359)
    static let textJustify: Self                = .init(62360)
    static let suitcases: Self                  = .init(62464)
    static let petCarrier: Self                 = .init(62465)
    static let airplaneLanded: Self             = .init(62466)
    static let airplaneCloud: Self              = .init(62467)
    static let airplaneTicket: Self             = .init(62468)
    static let airplaneSeat: Self               = .init(62469)
    static let personWalkingSuitcase: Self      = .init(62470)
    static let appleClassicalPages: Self        = .init(62471)
    static let textSquareFilled: Self           = .init(62472)
    static let characterTextJustify: Self       = .init(62473)
    static let graph2D: Self                    = .init(62480)
    static let mathOperators: Self              = .init(62481)
    static let circle: Self                     = .init(62482)
    static let capsulePortrait: Self            = .init(62483)
    static let rectangle: Self                  = .init(62484)
    static let rectanglePortrait: Self          = .init(62485)
    static let oval: Self                       = .init(62486)
    static let ovalPortrait: Self               = .init(62487)
    static let triangle: Self                   = .init(62488)
    static let diamond: Self                    = .init(62489)
    static let octagon: Self                    = .init(62496)
    static let hexagon: Self                    = .init(62497)
    static let pentagon: Self                   = .init(62498)
    static let seal: Self                       = .init(62499)
    static let rhombus: Self                    = .init(62500)
    static let shield: Self                     = .init(62501)
    static let shazam: Self                     = .init(61796)
    static let blank: Self                      = .init(999999)
}

extension Icon {
    public struct Color: Encodable, Sendable {
        public var red: UInt8
        public var green: UInt8
        public var blue: UInt8
        public var alpha: UInt8
        
        public init(_ red: UInt8, _ green: UInt8, _ blue: UInt8, _ alpha: UInt8 = .max) {
            self.red = red
            self.green = green
            self.blue = blue
            self.alpha = alpha
        }
        
        public func encode(to encoder: any Encoder) throws {
            let integer = (
                Int(red)   << 24 |
                Int(green) << 16 |
                Int(blue)  << 8  |
                Int(alpha)
            )
            
            try integer.encode(to: encoder)
        }
    }
}

extension Icon.Color {
    public static let red: Self        = .init(255, 069, 058)
    public static let darkorange: Self = .init(255, 159, 010)
    public static let orange: Self     = .init(255, 149, 000)
    public static let yellow: Self     = .init(255, 204, 000)
    public static let green: Self      = .init(052, 199, 089)
    public static let teal: Self       = .init(090, 200, 250)
    public static let lightblue: Self  = .init(000, 122, 255)
    public static let blue: Self       = .init(088, 086, 214)
    public static let darkblue: Self   = .init(000, 064, 221)
    public static let violet: Self     = .init(175, 082, 222)
    public static let purple: Self     = .init(191, 090, 242)
    public static let pink: Self       = .init(255, 045, 085)
    public static let darkgray: Self   = .init(000, 000, 000)
    public static let gray: Self       = .init(142, 142, 147)
    public static let taupe: Self      = .init(162, 132, 094)
}
